# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=50)),
                ('int_x', models.IntegerField()),
                ('int_y', models.IntegerField()),
                ('int_z', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
