# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample1',
        ),
    ]
