# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_sample1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='int_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='int_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='int_z',
            field=models.FloatField(),
        ),
    ]
