# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160305_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='int_x',
            new_name='value_x',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='int_y',
            new_name='value_y',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='int_z',
            new_name='value_z',
        ),
    ]
